//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeneratorTest.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GeneratorTest.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   using Codeer.Friendly.Dynamic;
        ///using Codeer.Friendly.Windows;
        ///using Codeer.Friendly.Windows.Grasp;
        ///using Codeer.TestAssistant.GeneratorToolKit;
        ///using Ong.Friendly.FormsStandardControls;
        ///
        ///namespace TestCode
        ///{
        ///    [WindowDriver(TypeFullName = &quot;CreateDriverTarget.SingleForm&quot;)]
        ///    public class SingleForm_Driver
        ///    {
        ///        public WindowControl Core { get; }
        ///        public FormsToolStrip toolStrip1 =&gt; new FormsToolStrip(Core.Dynamic().toolStrip1);
        ///        public FormsToolStrip menuStrip1 =&gt; new F [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MdiChildForm_Driver {
            get {
                return ResourceManager.GetString("MdiChildForm_Driver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   using Codeer.Friendly.Dynamic;
        ///using Codeer.Friendly.Windows;
        ///using Codeer.Friendly.Windows.Grasp;
        ///using Codeer.TestAssistant.GeneratorToolKit;
        ///using Ong.Friendly.FormsStandardControls;
        ///
        ///namespace TestCode
        ///{
        ///    [WindowDriver(TypeFullName = &quot;CreateDriverTarget.MdiParentForm&quot;)]
        ///    public class MdiParentForm_Driver
        ///    {
        ///        public WindowControl Core { get; }
        ///        public FormsMonthCalendar MonthCalendar =&gt; new FormsMonthCalendar(Core.IdentifyFromTypeFullName(&quot;System.Windows.Forms.MonthCale [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MdiParentForm_Driver {
            get {
                return ResourceManager.GetString("MdiParentForm_Driver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   using Codeer.Friendly.Dynamic;
        ///using Codeer.Friendly.Windows;
        ///using Codeer.Friendly.Windows.Grasp;
        ///using Codeer.TestAssistant.GeneratorToolKit;
        ///using Ong.Friendly.FormsStandardControls;
        ///using System.Linq;
        ///
        ///namespace TestCode
        ///{
        ///    [UserControlDriver(TypeFullName = &quot;CreateDriverTarget.UserControl1&quot;)]
        ///    public class UserControl1_Driver
        ///    {
        ///        public WindowControl Core { get; }
        ///        public FormsToolStrip menuStrip1 =&gt; new FormsToolStrip(Core.Dynamic().menuStrip1);
        ///        public Forms [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NestedUserControl1_Driver {
            get {
                return ResourceManager.GetString("NestedUserControl1_Driver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   using Codeer.Friendly.Dynamic;
        ///using Codeer.Friendly.Windows;
        ///using Codeer.Friendly.Windows.Grasp;
        ///using Codeer.TestAssistant.GeneratorToolKit;
        ///using Ong.Friendly.FormsStandardControls;
        ///
        ///namespace TestCode
        ///{
        ///    [WindowDriver(TypeFullName = &quot;CreateDriverTarget.SingleForm&quot;)]
        ///    public class SingleForm_Driver
        ///    {
        ///        public WindowControl Core { get; }
        ///        public FormsToolStrip toolStrip1 =&gt; new FormsToolStrip(Core.Dynamic().toolStrip1);
        ///        public FormsToolStrip menuStrip1 =&gt; new F [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SingleForm_Driver {
            get {
                return ResourceManager.GetString("SingleForm_Driver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   using Codeer.Friendly.Dynamic;
        ///using Codeer.Friendly.Windows;
        ///using Codeer.Friendly.Windows.Grasp;
        ///using Codeer.TestAssistant.GeneratorToolKit;
        ///using Ong.Friendly.FormsStandardControls;
        ///
        ///namespace TestCode
        ///{
        ///    [WindowDriver(TypeFullName = &quot;CreateDriverTarget.TabUserControlForm&quot;)]
        ///    public class TabUserControlForm_Driver
        ///    {
        ///        public WindowControl Core { get; }
        ///        public FormsTabControl tabControl1 =&gt; new FormsTabControl(Core.Dynamic().tabControl1);
        ///        public UserControl2_D [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TabUserControlForm_Driver {
            get {
                return ResourceManager.GetString("TabUserControlForm_Driver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   using Codeer.Friendly.Dynamic;
        ///using Codeer.Friendly.Windows;
        ///using Codeer.Friendly.Windows.Grasp;
        ///using Codeer.TestAssistant.GeneratorToolKit;
        ///using Ong.Friendly.FormsStandardControls;
        ///
        ///namespace TestCode
        ///{
        ///    [UserControlDriver(TypeFullName = &quot;CreateDriverTarget.UserControl1&quot;)]
        ///    public class UserControl1_Driver
        ///    {
        ///        public WindowControl Core { get; }
        ///        public FormsToolStrip menuStrip1 =&gt; new FormsToolStrip(Core.Dynamic().menuStrip1);
        ///        public FormsToolStrip toolStrip1 [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UserControl1_Driver {
            get {
                return ResourceManager.GetString("UserControl1_Driver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   using Codeer.Friendly.Dynamic;
        ///using Codeer.Friendly.Windows;
        ///using Codeer.Friendly.Windows.Grasp;
        ///using Codeer.TestAssistant.GeneratorToolKit;
        ///using Ong.Friendly.FormsStandardControls;
        ///
        ///namespace TestCode
        ///{
        ///    [UserControlDriver(TypeFullName = &quot;CreateDriverTarget.UserControl2&quot;)]
        ///    public class UserControl2_Driver
        ///    {
        ///        public WindowControl Core { get; }
        ///        public FormsButton button1 =&gt; new FormsButton(Core.Dynamic().button1);
        ///        public FormsCheckBox checkBox1 =&gt; new FormsC [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UserControl2_Driver {
            get {
                return ResourceManager.GetString("UserControl2_Driver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   using Codeer.Friendly.Dynamic;
        ///using Codeer.Friendly.Windows;
        ///using Codeer.Friendly.Windows.Grasp;
        ///using Codeer.TestAssistant.GeneratorToolKit;
        ///
        ///namespace TestCode
        ///{
        ///    [WindowDriver(TypeFullName = &quot;CreateDriverTarget.UserControlForm&quot;)]
        ///    public class UserControlForm_Driver
        ///    {
        ///        public WindowControl Core { get; }
        ///        public UserControl1_Driver userControl11 =&gt; new UserControl1_Driver(new WindowControl(Core.Dynamic().userControl11));
        ///
        ///        public UserControlForm_Driver(WindowC [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UserControlForm_Driver {
            get {
                return ResourceManager.GetString("UserControlForm_Driver", resourceCulture);
            }
        }
    }
}
